-- ============================================================
-- Hasan Babu Ka Aspataal - Clinic Management System
-- Database Schema (MySQL)
-- ============================================================

CREATE DATABASE IF NOT EXISTS hasan_babu_clinic
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE hasan_babu_clinic;

-- ------------------------------------------------------------
-- USERS TABLE  (Doctor, Reception, Pharmacy, Admin - sabhi
-- isi table se login karte hain, role field se differentiate)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id            INT AUTO_INCREMENT PRIMARY KEY,
    full_name     VARCHAR(150)  NOT NULL,
    username      VARCHAR(100)  NOT NULL UNIQUE,
    password_hash VARCHAR(255)  NOT NULL,
    role          ENUM('doctor', 'reception', 'pharmacy', 'admin') NOT NULL,
    phone         VARCHAR(20),
    is_active     BOOLEAN DEFAULT TRUE,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------------------------
-- PATIENTS TABLE
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS patients (
    id            INT AUTO_INCREMENT PRIMARY KEY,
    hba_id        VARCHAR(20) NOT NULL UNIQUE,   -- e.g. HBA-0001
    full_name     VARCHAR(150) NOT NULL,
    age           INT,
    gender        ENUM('Male', 'Female', 'Other'),
    phone         VARCHAR(20),
    address       TEXT,
    guardian_name VARCHAR(150),
    photo_path    VARCHAR(255),
    registered_by INT,                            -- FK -> users.id
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (registered_by) REFERENCES users(id)
);

-- ------------------------------------------------------------
-- OPD VISITS / QUEUE TABLE
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS opd_visits (
    id            INT AUTO_INCREMENT PRIMARY KEY,
    patient_id    INT NOT NULL,
    token_number  INT NOT NULL,
    visit_date    DATE NOT NULL DEFAULT (CURRENT_DATE),
    status        ENUM('waiting', 'with_doctor', 'completed', 'cancelled') DEFAULT 'waiting',
    complaint     TEXT,
    diagnosis     TEXT,
    prescription  TEXT,
    seen_by       INT,                             -- FK -> users.id (doctor)
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(id),
    FOREIGN KEY (seen_by) REFERENCES users(id)
);

-- ------------------------------------------------------------
-- MEDICINES / PHARMACY INVENTORY
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS medicines (
    id            INT AUTO_INCREMENT PRIMARY KEY,
    name          VARCHAR(150) NOT NULL,
    batch_no      VARCHAR(50),
    quantity      INT DEFAULT 0,
    unit_price    DECIMAL(10,2),
    expiry_date   DATE,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Seed one admin user (password: admin123 -> bcrypt hash to be generated by backend on first run)
-- INSERT INTO users (full_name, username, password_hash, role) VALUES
-- ('Admin', 'admin', '$2b$10$replace_with_real_hash', 'admin');
